Test ng hw
KhramtsovaV/AQA27Onl pull request #1
Opened 2024-07-01 15:24 UTC by KhramtsovaV

RetryTest in progress need more time

2024-07-02 11:16 UTC, wildpioneer requested changes

2024-07-02 11:16 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +    public void testDivisionIntWithPositiveNumbers() {
Почему-то файл Calculator.class не попал в PR -  а там ошибки
public static int div(int a, int b){
        if (b==0) {
            throw new ArithmeticException("division by zero");
        }
        return a / b;
    }

Никаких обработок в методе быть не должно

2024-07-02 11:16 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +            double result = Calculator.div(10.34, 0);
Нужно будет переделать после исправления самих методов деления

2024-07-02 11:16 UTC, wildpioneer commented on src/test/java/CalcTest.java
> +        Assert.assertEquals(Calculator.div(10.0, -5.0),-2);
Отсутствует тест на деление 0/0

2024-07-02 11:16 UTC, wildpioneer commented on src/test/java/RetryTest.java
> +
Отсутствуют тесты с атрибутами:
- testName,
- expectedExceptions,
- @Parameters

2024-07-03 16:16 UTC, KhramtsovaV commented on src/test/java/RetryTest.java
> +
исправила

2024-07-03 16:18 UTC, KhramtsovaV commented on src/test/java/CalcTest.java
> +    public void testDivisionIntWithPositiveNumbers() {
убрала обработку ArithmeticException https://github.com/KhramtsovaV/AQA27Onl/pull/1/commits/746ee941308674de8ab4214e4142a3206218025e

2024-07-03 16:18 UTC, KhramtsovaV commented on src/test/java/CalcTest.java
> +        Assert.assertEquals(Calculator.div(10.0, -5.0),-2);
добавила

2024-07-15 14:29 UTC, wildpioneer commented
Проверено

2024-07-15 14:29 UTC, closed without merging