Web driver hw
KhramtsovaV/AQA27Onl pull request #2
Opened 2024-07-10 19:59 UTC by KhramtsovaV

2024-07-15 14:37 UTC, wildpioneer requested changes

2024-07-15 14:37 UTC, wildpioneer commented on src/test/java/tests/Task3.java
> +        Assert.assertEquals(value1,0.39);
Тут у тебя проблема - потому что ты пытаешься String сравнить с Int
Должно быть  Assert.assertEquals(value1, "0.39"); - и в таком случае все получается

2024-07-15 14:44 UTC, KhramtsovaV commented on src/test/java/tests/Task3.java
> +        Assert.assertEquals(value1,0.39);
Кавычки ТОЧНО! Спасибо!!

2024-07-25 13:19 UTC, wildpioneer commented
Проверено

2024-07-25 13:19 UTC, closed without merging